// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcf9LIbxNxzF6a8URXq-yL-b2IsYAYPxE',
    appId: '1:778170953436:web:b9b7674dd41f6d96ce8e19',
    messagingSenderId: '778170953436',
    projectId: 'project-luarsekolah',
    authDomain: 'project-luarsekolah.firebaseapp.com',
    storageBucket: 'project-luarsekolah.firebasestorage.app',
    measurementId: 'G-0K7ZF74MZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIwohRzNNwxyt6dt--wBPudGj8RdxTIe4',
    appId: '1:778170953436:android:a032ede483ed2279ce8e19',
    messagingSenderId: '778170953436',
    projectId: 'project-luarsekolah',
    storageBucket: 'project-luarsekolah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY_lJWUwpozQE1yuRck63UPVqYq9Q9yNo',
    appId: '1:778170953436:ios:289f6c032b957220ce8e19',
    messagingSenderId: '778170953436',
    projectId: 'project-luarsekolah',
    storageBucket: 'project-luarsekolah.firebasestorage.app',
    iosBundleId: 'com.example.projectluarsekolah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY_lJWUwpozQE1yuRck63UPVqYq9Q9yNo',
    appId: '1:778170953436:ios:289f6c032b957220ce8e19',
    messagingSenderId: '778170953436',
    projectId: 'project-luarsekolah',
    storageBucket: 'project-luarsekolah.firebasestorage.app',
    iosBundleId: 'com.example.projectluarsekolah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcf9LIbxNxzF6a8URXq-yL-b2IsYAYPxE',
    appId: '1:778170953436:web:d5d21a3103f05016ce8e19',
    messagingSenderId: '778170953436',
    projectId: 'project-luarsekolah',
    authDomain: 'project-luarsekolah.firebaseapp.com',
    storageBucket: 'project-luarsekolah.firebasestorage.app',
    measurementId: 'G-9YY9HF7Q86',
  );

}